version: 2.1

jobs:
  hello-job:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command

workflows:
  my-workflow:
    jobs:
      - hello-job
